apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: metrics-forwarder
spec:
  scopes:
    - Namespaced
  phases:
    - name: certman-issuer
      objects:
      - object: {apiVersion: cert-manager.io/v1, kind: Issuer}
    - name: certman-cert
      objects:
      - object: {apiVersion: cert-manager.io/v1, kind: Certificate}
    - name: config
      objects:
      - object: {apiVersion: v1, kind: ConfigMap}
    - name: deploy
      objects:
      - object: {apiVersion: apps, kind: Deployment}
    - name: expose
      objects:
      - object: {apiVersion: v1, kind: Service}
      - object: {apiVersion: route.openshift.io/v1, kind: Route}
  availabilityProbes:
    - selector:
        kind:
          groups: cert-manager.io
          kind: Issuer
      probes:
      - condition:
          type: Ready
          status: "True"
test:
  template:
  # default HyperShift HCP template test.
  - name: default
    context:
      package:
        metadata:
          name: metrics-forwarder
          namespace: ocm-staging-24o19ba52km496nvegb629918l9gbnvu-bmeng-hcp
